const { app, BrowserWindow, ipcMain } = require('electron');
const path = require('path');

// --- Dynamic Import electron-store --- 
let store;

async function initializeStore() {
  if (!store) {
    try {
      const { default: Store } = await import('electron-store');
      store = new Store();
      console.log('Electron Store initialized successfully.');
    } catch (error) {
      console.error('Failed to dynamically import or initialize electron-store:', error);
      // Handle the error appropriately - maybe quit the app or disable features
      // For now, we'll just log it.
    }
  }
  return store; // Return the initialized store instance
}

// --- Initialize store before setting up IPC handlers that need it ---
async function setupIpcHandlers() {
  const store = await initializeStore();

  // --- Settings Storage Handlers ---
  ipcMain.handle('settings:get-api-key', async () => {
    if (!store) return '';
    return store.get('openai-api-key', '');
  });

  ipcMain.handle('settings:set-api-key', async (event, apiKey) => {
    if (!store) return { success: false, error: 'Store not initialized' };
    store.set('openai-api-key', apiKey);
    console.log('API Key updated (storage)');
    return { success: true };
  });

  // --- Audio Device Storage Handlers --- 
  ipcMain.handle('settings:get-audio-device', async () => {
    if (!store) return ''; 
    return store.get('audio-device-id', '');
  });

  ipcMain.handle('settings:set-audio-device', async (event, deviceId) => {
    if (!store) return { success: false, error: 'Store not initialized' };
    store.set('audio-device-id', deviceId);
    console.log('Audio Device ID saved:', deviceId);
    return { success: true };
  });

  // --- Logging Handler ---
  ipcMain.on('renderer:log', (event, { level, message, data }) => {
    console[level](`[Renderer] ${message}`, data || '');
  });
}

// Global error handlers for the main process
process.on('uncaughtException', (error) => {
  console.error('[Main] Uncaught Exception:', error);
});

process.on('unhandledRejection', (reason, promise) => {
  console.error('[Main] Unhandled Promise Rejection:', reason);
});

function createWindow () {
  const mainWindow = new BrowserWindow({
    width: 950,
    height: 950,
    resizable: false, // Make the window non-resizable
    // icon: path.join(__dirname, '../assets/icon.png'), // Uncomment when you have the icon
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'), // Re-enabled preload script
      nodeIntegration: false, // Keep disabled for security
      contextIsolation: true, // Explicitly true (default, but good practice)
      webSecurity: process.env.NODE_ENV !== 'development' // Keep this or adjust as needed
    }
  });

  // Forward console logs from renderer to main process terminal
  mainWindow.webContents.on('console-message', (event, level, message, line, sourceId) => {
    const levels = ['debug', 'log', 'info', 'warn', 'error'];
    const prefix = sourceId ? `[Renderer:${sourceId.split('/').pop()}:${line}]` : '[Renderer]';
    
    switch (level) {
      case 0: // debug
        console.debug(`${prefix} ${message}`);
        break;
      case 1: // log
        console.log(`${prefix} ${message}`);
        break;
      case 2: // info
        console.info(`${prefix} ${message}`);
        break;
      case 3: // warn
        console.warn(`${prefix} ${message}`);
        break;
      case 4: // error
        console.error(`${prefix} ${message}`);
        break;
      default:
        console.log(`${prefix} [${levels[level] || level}] ${message}`);
    }
  });

  // Capture uncaught errors and exceptions from renderer
  mainWindow.webContents.on('crashed', () => {
    console.error('[Renderer] WebContents crashed');
  });

  mainWindow.on('unresponsive', () => {
    console.error('[Renderer] Window became unresponsive');
  });

  // Remove menu bar in production
  if (app.isPackaged) {
    mainWindow.removeMenu();
    console.log('Removed menu bar for packaged app.');
  }

  // Load index.html generated by Webpack
  // Use loadFile for development, loadURL for production build with file protocol
  // mainWindow.loadFile(path.join(__dirname, '../renderer/index.html')); // Old path
  if (process.env.NODE_ENV === 'development') {
    // In development, load from the webpack dev server or watcher output
    // Use loadFile assuming webpack watch outputs to renderer/dist
    mainWindow.loadFile(path.join(__dirname, '../renderer/dist/index.html')); 
  } else {
    // In production, load the bundled HTML file from within app.asar
    // Path relative to main.js (which is in app.asar/main)
    mainWindow.loadFile(path.join(__dirname, '../renderer/dist/index.html'));
  }

  // Open DevTools in development mode
  if (process.env.NODE_ENV === 'development') {
    mainWindow.webContents.openDevTools();
  }
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(async () => { // Make the handler async
  await setupIpcHandlers(); // Wait for handlers (and store) to be ready
  createWindow();

  app.on('activate', function () {
    // On macOS it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

// Quit when all windows are closed, no matter which platform
app.on('window-all-closed', function () {
  app.quit();
});

// Ensure OpenAI and other requires are still available where needed
// If they are only used within IPC handlers, they can stay there.
// If needed elsewhere, ensure they are required appropriately.
const { OpenAI } = require("openai");
const { toFile } = require("openai/uploads"); 